### ISSUE TITLE
Lab 1: Please add that unzip_requirements.py file to repo

### ISSUE THREAD

**Issue by uzair004** [soumilshah1995/install-external-python-packages-on-serverless#2]
In the tutorial, you emphasized including unzip_requirements at top of the file. I can see you have that file in the tutorial but not available in the repo, we need to know whats in there.

**Comment by soumilshah1995** [comment]
Hi i just checked lab1 
```
try:
    import unzip_requirements
except ImportError:
    pass
```

i think unzip is already added in python file
